# Configuration for analysis
CYCLE_GAP_MAX_DAYS = 30
DUE_THRESHOLD = 30
DUE_TOP_N = 5
EXHAUSTED_GAP_THRESHOLD = 0
HOT_LOOKBACK_DAYS = 7
HOT_TOP_N = 3
EXHAUSTED_LOOKBACK_DAYS = 7
EXHAUSTED_BOTTOM_N = 3
TOP_PICKS_COUNT = 3
